<?php

/**
 * @file
 * Contains socion.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function socion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the socion module.
    case 'help.page.socion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for the analysis of socionic types') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function socion_theme() {
  $theme = [];
  $theme['socionics_type_entity'] = [
    'render element' => 'elements',
    'file' => 'socionics_type_entity.page.inc',
    'template' => 'socionics_type_entity',
  ];
  $theme['socionics_type_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'socionics_type_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function socion_theme_suggestions_socionics_type_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#socionics_type_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'socionics_type_entity__' . $sanitized_view_mode;
  $suggestions[] = 'socionics_type_entity__' . $entity->bundle();
  $suggestions[] = 'socionics_type_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'socionics_type_entity__' . $entity->id();
  $suggestions[] = 'socionics_type_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
