<?php

/**
 * @file
 * Contains socion.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function socion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.range_slider':
      $text = file_get_contents(dirname(__FILE__) . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      // Use the Markdown filter to render the README.
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
      $config = ['settings' => $settings];
      $filter = $filter_manager->createInstance('markdown', $config);
      return $filter->process($text, 'en');
  }
  return NULL;
}

/**
 * Implements hook_theme().
 */
function socion_theme() {
  $theme = [];
  $theme['socionics_type_entity'] = [
    'render element' => 'elements',
    'file' => 'socionics_type_entity.page.inc',
    'template' => 'socionics_type_entity',
  ];
  $theme['socion_form'] = [
    'render element' => 'form'
  ];
  $theme['socionics_type_entity_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'socionics_type_entity.page.inc',
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function socion_theme_suggestions_socionics_type_entity(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#socionics_type_entity'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'socionics_type_entity__' . $sanitized_view_mode;
  $suggestions[] = 'socionics_type_entity__' . $entity->bundle();
  $suggestions[] = 'socionics_type_entity__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'socionics_type_entity__' . $entity->id();
  $suggestions[] = 'socionics_type_entity__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
